version: '2'

services:
  jenkins:
    build: ./server
    container_name: 'jenkins'
    ports:
      - '80:8080'
    environment:
      - JENKINS_PASSWORD=bitnami
    volumes:
      - jenkins_data:/bitnami/jenkins
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_data:
    driver: local

